select * from cleaned_website_sessions
select * from cleaned_orders;
-- Order to Session Ratio or Conversion rate(Visitor-Customer)
create view conversion_rate as 
with cte_1 as(
	select count(distinct website_session_id) orders from cleaned_orders
),cte_2 as(
	select count(distinct website_session_id) sessions from cleaned_website_sessions
)select cte_1.orders,cte_2.sessions,(100.0 *cte_1.orders/cte_2.sessions)[Conversion Rate] from cte_1 cross join cte_2;
go
-- Number and Ratio of orders per session grouped by the source
with cte_3 as(
	select ws.utm_source[Source],count(distinct o.website_session_id) orders from cleaned_orders o join [dbo].[cleaned_website_sessions] ws on o.website_session_id=ws.website_session_id group by ws.utm_source
),cte_4 as(
	select ws.utm_source[Source],count(distinct ws.website_session_id) [Count of sessions] from cleaned_website_sessions ws group by ws.utm_source
)select cte_3.[Source],cte_3.orders,cte_4.[Count of Sessions],(100.0 *cte_3.orders/cte_4.[Count of sessions]) as[percentage by source] from cte_3 join cte_4 on cte_3.[Source]=cte_4.[Source] order by [percentage by source] desc
-- UTM Campaign wise Website sessions
select count(*),coalesce(utm_campaign,'direct') from [dbo].[cleaned_website_sessions] group by coalesce(utm_campaign,'direct')
select count(utm_campaign),coalesce(utm_campaign,'direct') from [dbo].[cleaned_website_sessions] group by coalesce(utm_campaign,'direct')
-- Total count of campaigns in website Sessions Table
select count(*),utm_campaign from [dbo].[cleaned_website_sessions] group by utm_campaign
-- Distinct UTM Campaigns
select distinct (utm_campaign) from [dbo].[cleaned_website_sessions]

--How many and what campaigns led to product item being bought?
select coalesce(ws.utm_campaign,'direct')[Campaign Name],count(*)[Marketing campaign that led to the order] from [dbo].[cleaned_website_sessions] ws join [dbo].[cleaned_orders] o on ws.website_session_id=o.website_session_id group by coalesce(ws.utm_campaign,'direct') order by [Marketing campaign that led to the order] desc

--Percentage success by campaign
with cte_5 as(
	select coalesce(utm_campaign,'direct')[Campaign type],count(*)[Count of marketing campaign] from [dbo].[cleaned_website_sessions] group by coalesce(utm_campaign,'direct')

),cte_6 as(
	select coalesce(ws.utm_campaign,'direct')[Campaign type],count(*)[Marketing campaign that led to the order] from [dbo].[cleaned_website_sessions] ws join [dbo].[cleaned_orders] o on ws.website_session_id=o.website_session_id group by coalesce(ws.utm_campaign,'direct') 
)select cte_6.[Campaign type],cte_5.[Count of marketing campaign],cte_6.[Marketing campaign that led to the order],(100.0*cte_6.[Marketing campaign that led to the order]/cte_5.[Count of marketing campaign])[Percentage of Marketing campaign success] from cte_5 join cte_6 on cte_5.[Campaign type]=cte_6.[Campaign type] order by [Percentage of Marketing campaign success] desc

---Revenue generated by each Campaign
with cte_7 as(
	select [website_session_id],coalesce([utm_campaign],'direct')[Campaign type] from [dbo].[cleaned_website_sessions]
),cte_8 as(
	select [website_session_id],[price_usd] from [dbo].[cleaned_orders]
)select cte_7.[Campaign type],sum(cte_8.[price_usd])[Revenue of the Campaign] from cte_7 join cte_8 on cte_7.website_session_id=cte_8.website_session_id group by cte_7.[Campaign type] order by [Revenue of the Campaign] desc;

--conversion rate by device
    --total number of sesssions per device type
select [device_type],count(*) from [dbo].[cleaned_website_sessions] group by [device_type]
select [device_type],count(*) from [dbo].[cleaned_website_sessions] ws join [dbo].[cleaned_orders] o on ws.website_session_id=o.website_session_id group by ws.[device_type];
with cte_9 as(
	select [device_type],count(*)[Count] from [dbo].[cleaned_website_sessions] group by [device_type]
),cte_10 as(
	select [device_type],count(*)[Count] from [dbo].[cleaned_website_sessions] ws join [dbo].[cleaned_orders] o on ws.website_session_id=o.website_session_id group by ws.[device_type]
)select cte_9.device_type, (100.0* cte_10.[Count]/cte_9.[Count])[Percentage] from cte_9 join cte_10 on cte_9.device_type=cte_10.device_type order by [Percentage] desc;
-- Profit Margin by Product
select p.product_id,p.product_name,sum(o.profit)[Profit] from [dbo].[cleaned_orders] o left join [dbo].[cleaned_order_items] i on o.order_id=i.order_id left join [dbo].[cleaned_products] p on i.product_id=p.product_id group  by p.product_id,p.product_name order by [Profit] desc

select p.product_id,p.product_name,(100.0 * sum(o.profit)/sum(o.price_usd))[Profit Margin] from [dbo].[cleaned_order_items] o join [dbo].[cleaned_products] p on o.[product_id]=p.[product_id] group by p.product_name,p.product_id order by [Profit Margin] desc;

--- Classification of Orders into high low,medium(Usage of Case)
select price_usd from cleaned_orders group by price_usd order by price_usd desc
select order_id,price_usd,
	case when price_usd<50 then 'Low'
	when price_usd<90 then'Medium'
	when price_usd>90 then 'High'
	else 'Uncategorized' 
end from [dbo].[cleaned_orders] 

select
	case  when price_usd<50 then 'Low'
	when price_usd<90 then'Medium'
	when price_usd>90 then 'High'
	else 'Uncategorized' end [order_type],count(*)[Count] from  [dbo].[cleaned_orders] 
	group by case when price_usd<50 then 'Low'
	when price_usd<90 then'Medium'
	when price_usd>90 then 'High'
	else 'Uncategorized' end
---Classification of Customers into new,repeat and loyal
1