alter table [dbo].[cleaned_order_items] 
add profit float
update [dbo].[cleaned_order_items] set profit=[price_usd]-[cogs_usd]
alter table [dbo].[cleaned_orders]
add profit float
update [dbo].[cleaned_orders] set profit=[price_usd]-[cogs_usd]
-- Count of Maximum Selling Product
select o.product_id,p.product_name,count(*) [Count of Each Selling item]  from cleaned_order_items o

left join cleaned_products p on o.product_id=p.product_id
group by o.product_id,p.product_name order by [Count of Each Selling item] desc;

-- Revenue of Maximum Selling Product
select o.product_id,sum(o.price_usd)[Revenue],p.product_name from [dbo].[cleaned_order_items] o left join [dbo].[cleaned_products] p on o.product_id=p.product_id group by o.product_id,p.product_name order by [Revenue] desc;
-- Profit Generated by each Product
select o.product_id,p.product_name,sum(o.profit)[Profit] from [dbo].[cleaned_order_items] o left join [dbo].[cleaned_products] p on o.product_id=p.product_id group by o.product_id,p.product_name order by [Profit] desc;

---Maximum refund issued for which product
select * from cleaned_order_refunds

select p.product_id,p.product_name,count(*) [Times Refund Issued] from [dbo].[cleaned_order_refunds] r left join [dbo].[cleaned_order_items] o on r.order_item_id=o.order_item_id left join [dbo].[cleaned_products] p on o.product_id=p.product_id group by p.product_id,p.product_name order by [Times Refund Issued] desc;

---refund amount
select p.product_id,p.product_name,sum(r.refund_amount_usd) [Refund Amount Issued] from [dbo].[cleaned_order_refunds] r left join [dbo].[cleaned_order_items] o on r.order_item_id=o.order_item_id left join [dbo].[cleaned_products] p on o.product_id=p.product_id group by p.product_id,p.product_name order by [Refund Amount Issued] desc;

-- Which user had the maximum refunds issued?
select o.user_id,count(*)[Number Of Times Refund issued],sum(r.refund_amount_usd) [Refund Amount Issued] from [dbo].[cleaned_order_refunds] r left join [dbo].[cleaned_orders] o on r.order_id=o.order_id group by o.user_id order by [Refund Amount Issued] desc,count(*) desc;
--- Refund Rate by product
with cte_1 as(
	select o.product_id,p.product_name,count(*) [Count of Each Selling item]  from cleaned_order_items o
	left join cleaned_products p on o.product_id=p.product_id
	group by o.product_id,p.product_name
),cte_2 as(
	select p.product_id,p.product_name,count(*) [Times Refund Issued] from [dbo].[cleaned_order_refunds] r left join [dbo].[cleaned_order_items] o on r.order_item_id=o.order_item_id left join [dbo].[cleaned_products] p on o.product_id=p.product_id group by p.product_id,p.product_name
)select *,cte_1.[Count of Each Selling item]/cte_2.[Times Refund Issued][One in how many times was refunded],(100.0* cte_2.[Times Refund Issued]/cte_1.[Count of Each Selling item])[Percentage of Items Refunded] from cte_1 join cte_2 on cte_1.product_id=cte_2.product_id order by [Percentage of Items Refunded] desc;

-- Number of Primary Items Refunded
select p.product_id,p.product_name,count(*) [Times Refund Issued for Primary Iteem] from [dbo].[cleaned_order_refunds] r left join [dbo].[cleaned_order_items] o on r.order_item_id=o.order_item_id left join [dbo].[cleaned_products] p on o.product_id=p.product_id where o.is_primary_item=1 group by p.product_id,p.product_name order by [Times Refund Issued for Primary Iteem] desc;
-- Profit Margin by Product
select p.product_id,p.product_name,sum(o.profit)[Profit] from [dbo].[cleaned_orders] o left join [dbo].[cleaned_order_items] i on o.order_id=i.order_id left join [dbo].[cleaned_products] p on i.product_id=p.product_id group  by p.product_id,p.product_name order by [Profit] desc

select p.product_id,p.product_name,(100.0 * sum(o.profit)/sum(o.price_usd))[Profit Margin] from [dbo].[cleaned_order_items] o join [dbo].[cleaned_products] p on o.[product_id]=p.[product_id] group by p.product_name,p.product_id order by [Profit Margin] desc;
---Which user never visted the website again?
select count(*) from (select user_id,count(*)[Count] from [dbo].[cleaned_website_sessions] group by user_id having count(*)=1) as [Count]
select user_id,count(*)from [dbo].[cleaned_website_sessions] group by user_id having count(*)=1;

select user_id,count(*) from [dbo].[cleaned_website_sessions] group by user_id order by count(*) desc

select count(distinct user_id) from [dbo].[cleaned_website_sessions] ws
select count(*) from (select distinct user_id,count(*)[Count] from [dbo].[cleaned_website_sessions] group by user_id having count(*)>1) as [Count]


--Average Number of times a user has returned to wewbsite
select avg(CAST([Number of time user visited website] as float)) from (select user_id,count(*)[Number of time user visited website] from [dbo].[cleaned_website_sessions] group by user_id) as t;
SELECT AVG(session_count) AS avg_sessions_per_user
FROM (
    SELECT user_id,
           COUNT(*) AS session_count
    FROM cleaned_website_sessions
    GROUP BY user_id
) t;

--- Average order Value
select avg(price_usd)[Average Price] from cleaned_orders
--Revenue per session
select sum(o.price_usd)/count(ws.website_session_id) from cleaned_orders o right join cleaned_website_sessions ws on o.website_session_id=ws.website_session_id
---Revenue by Repeat Customers
select user_id,count(*) from [dbo].[cleaned_orders] group by user_id order by count(*) desc;
with cte_2 as(
	select case when count(*)=1 then 'New' when count(*)=2 then 'Repeated' when count(*)>2 then 'Loyal' end  [Type of Customer],sum(price_usd)[Revenue] from [dbo].[cleaned_orders] group by user_id
)select cte_2.[Type of Customer] as[Type of Customer],sum(cte_2.Revenue)[Revenue] from cte_2 group by [Type of Customer]
--- Revenue by repeat Visitors
select user_id,count(*)[Number of Visits] from cleaned_website_sessions group by user_id order by [Number of Visits] desc
--- Visitors who didn't order
select * from [dbo].[cleaned_website_sessions] ws left anti join [dbo].[cleaned_orders] o on ws.[website_session_id]=o.[website_session_id] where o.user_id=ws.user_id
select distinct ws.user_id from dbo.cleaned_website_sessions ws where ws.user_id not in (select distinct user_id from dbo.cleaned_orders)
select count(distinct ws.user_id) from dbo.cleaned_website_sessions ws where ws.user_id not in (select distinct user_id from dbo.cleaned_orders)
select count(distinct user_id) from dbo.cleaned_website_sessions
select count(distinct user_id) from dbo.cleaned_orders
select ws.user_id from [dbo].[cleaned_website_sessions] ws left join [dbo].[cleaned_orders] o on ws.website_session_id=o.website_session_id where o.user_id is null;